version: 0.0
os: linux
files:
  - source: /build/*
    destination: /var/www/frontend
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/installing_dependencies
      timeout: 300
    - location: scripts/start_server
      timeout: 300
    - location: scripts/stop_server
      timeout: 300
