version: 0.0
os: linux
files:
  - source: /build
    destination: /var/www/frontend/
hooks:
  BeforeInstall:
    - location: script/install_dependencies
      timeout: 300
      runas: root
    - location: script/start_server
      timeout: 300
      runas: root
