---
version: 0.2
run-as: root

phases:
  install:
    commands:
      - yum install nodejs -y
      - yum install npm -y
  pre_build:
    commands:
      - cd frontend
      - curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
  build:
    commands:
      - npm install
      - npm install web-vitals
      - npm run build
  post_build:
    commands:
      - sed -i -e 's/\r$//' scripts/before_install.sh
      - sed -i -e 's/\r$//' scripts/after_install.sh
      - sed -i -e 's/\r$//' scripts/start_server.sh

artifacts:
   files:
     - frontend/public/**/*
     - frontend/src/**/*
     - frontend/package.json
     - appspec.yml
     - scripts/**/*
   discard-paths: no
