---
version: 0.2
run-as: root

phases:
  install:
    commands:
      - yum install nodejs -y
      - yum install npm -y
  pre_build:
    commands:
      - cd rontend
      - curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
  build:
    commands:
      - npm install
      - npm install web-vitals
      - npm run build
  post_build:
    commands:
      - cd ../
      - chmod +x scripts/*.sh
      - sed -i -e 's/\r$//' scripts/*.sh

artiacts:
   iles:
     - rontend/build/**/*
     - appspec.yml
     - scripts/**/*
   discard-paths: no
