version: 0.2
run-as: root

phases:
  install:
    commands:
      - sudo yum install nodejs -y
      - sudo yum install npm -y
  pre_build:
    commands:
      - cd frontend
      - curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
  build:
    commands:
      - npm install
      - npm run build
      
artifacts:
   files:
      - **-**
   discard-paths: no
   base-directory: frontend/build
